# English
dialog0 = "I see that you have made it to the castle's entrance. If you really are so strong, prove yourself by finding me. ^" # Lucien
dialog1 = "...? ^" # Sakura
dialog2 = "Hmm. I see that you have arrived. ^" # Lucien
dialog3 = "Hey! Are you the one releasing this horde upon the world? ^" # Sakura
dialog4 = "Heh, unfortunately, no. I am but his servant, and I have been commanded to kill any trespassers without question. Now come and perish. ^" # Lucien
dialog5 = "I do not understand. Who are you? ^" # Lucien
dialog6 = "My name is Sakura, ninja of Florere. I've come to destroy the monster releasing this horde of creatures upon my village! ^" # Sakura
dialog7 = "Hmph. I must confess, this 'monster' you speak of is my father. He is known as the Keeper of this castle, and is responsible for the attacks you speak of. ^" # Lucien
dialog8 = "And you're this Keeper fellow's son, sent to destroy any who might be lucky enough to enter the castle. Where can I find him? ^" # Sakura
dialog9 = "My father can be found deep within the castle, sitting on his throne in the Inner Sanctum. ^" # Lucien
dialog10 = "And why're you telling me this anyway? Aren't you supposed to be a bad guy? ^" # Sakura
dialog11 = "The Keeper of this castle is an oppressive master, and has for years threatened me with death if I did not obey to his forceful servitude. I do believe, with someone like you, I can relieve myself of this burden. ^" # Lucien
dialog12 = "So you're saying you wanna join me? ^" # Sakura
dialog13 = "Yes. With your aid, I do believe that I can vanquish our common foe. The one who has oppressed and tortured me for all my life. ^" # Lucien
dialog14 = "Well, OK, as long as you don't break your promise. ^" # Sakura
dialog15 = "I, Lucien, humbly and respectfully vow to not desert you in your quest for as long as I may live. ^" # Lucien
dialog16 = "You DO have some good in you, don'tcha Lucien? ^" # Sakura
dialog17 = "... ^" # Lucien
dialog18 = "Be on your guard. This is the largest section of Bloodmoor Castle, and many hazardous creatures lurk here. ^" # Lucien
dialog19 = "I'll be careful. ^" # Sakura
dialog20 = "Hey, Lucien, I just realized something. Notice how you ALWAYS sound so fancy? ^" # Sakura
dialog21 = "What? ^" # Lucien
dialog22 = "Oh, y'know, you sound so official all the time. Loosen up a bit, why don'tcha? ^" # Sakura
dialog23 = "Why does this trivial matter mean anything to you? ^" # Lucien
dialog24 = "Hahaha! ^" # Sakura
dialog25 = "We are here. Through this next door lies the guardian of the Main Hall. The infamous three-headed killer dog...Spot. ^" # Lucien
dialog26 = "Wait wait wait, this 'infamous killer dog' is named 'Spot'?! HAHAHA! ^" # Sakura
dialog27 = "It is no laughing matter! This dog has taken many a life at the command of The Keeper. Stay close; he will pounce. ^" # Lucien
dialog28 = "Okay fiiine, but it's still HILARIOUS. ^" # Sakura
dialog29 = "*huff* *puff* You weren't kidding, Lucien. That thing was TOUGH. ^" # Sakura
dialog30 = "Yes, a formidable foe indeed. Goodbye, dear old pet... ^" # Lucien
dialog31 = "Hmm hmm hmm. What a pretty one we have here... ^" # The Keeper
dialog32 = "*wimper* *wimper* Please don't hurt me. ^" # Aralis
dialog33 = "Servant, don't let this miserable wretch escape. You may resort to tortue, but by no means kill. I have use for her. ^" # The Keeper
dialog34 = "Heh heh. You ARE a pretty one, aren't you... ^" # Servant
dialog35 = "No! ^" # Aralis
dialog36 = "I gotta get out of here. Once I can retrieve my bow, I can make my escape. ^" # Aralis
dialog37 = "Aha! Now that I've got my bow, I can make my way out of here. ^" # Aralis
dialog38 = "Ah! Please stay away! ^" # Aralis
dialog39 = "Who...are you? ^" # Aralis
dialog40 = "Who am I? ^" # Sakura
dialog41 = "SAKURA MAKIMACHI, NINJA OF FLORERE! ^" # Sakura
dialog42 = "Lucien, son of The Keeper. ^" # Lucien
dialog43 = "We couldn't just LET these bad guys hurt you, now could we? ^" # Sakura
dialog44 = "... ^" # Aralis
dialog45 = "Thank you for saving me. ^" # Aralis
dialog46 = "Hmph. No problem. Though we must evacuate this area immediately, as we have caused a suspiciously large mess. ^" # Lucien
dialog47 = "You're taking me with you? ^" # Aralis
dialog48 = "Well, seeing as we're trying to destroy The Keeper, we can't point you to the exit. We can take you far enough though! ^" # Sakura
dialog49 = "I...I... ^" # Aralis
dialog50 = "Thank you. I can't let creeps like The Keeper scare me anymore, and I have to stand up for what is right! I would like to go with you. ^" # Aralis
dialog51 = "I suppose you may, but be aware of the dangers that await us on the way. ^" # Lucien
dialog52 = "Right! ^" # Aralis
dialog53 = "So, Aralis is it? Tell us how you got into this castle in the first place. ^" # Sakura
dialog54 = "I was summoned from my village to be a healer for the army. I would use my powers to tend to the wounds of soldiers injured by the evil creatures. The Keeper saw use for me, and instead of killing me with the others, he captured me and tried to force me to be a healer for his monsters and servants. ^" # Aralis
dialog55 = "I see. And how did you become so good at wielding the bow and arrow? ^" # Sakura
dialog56 = "I grew up in the village of Mistwood. After my parents died when I was a baby, the villagers took me in. My new father created and sold bows and arrows for a living, and he taught me how to wield them. ^" # Aralis
dialog57 = "A thousand pardons, but did you just say 'Mistwood'? ^" # Lucien
dialog58 = "Yes. Why, Lucien? ^" # Aralis
dialog59 = "Oh, don't mind me. ^" # Lucien
dialog60 = "... ^" # Lucien
dialog61 = "We have reached the Catacombs of the castle. Tread carefully here, for many of the castle's dead will rise again. ^" # Lucien
dialog62 = "Right. ^" # Sakura
dialog63 = "Right. ^" # Aralis
dialog64 = "Lucien, are you okay? I mean, you look sadder than usual. ^" # Sakura
dialog65 = "I...am fine. I will leave for a few minutes. Do not follow me. ^" # Lucien
dialog66 = "But- ^" # Aralis
dialog67 = "LEAVE ME ALONE! ^" # Lucien
dialog68 = "Lucien, Lucien, stupid boy. What is it that you're doing? Are you seriously considering joining this party of wretches? Destroying my creatures? DESERTING ME, YOUR FATHER?! ^" # The Keeper
dialog69 = "Father, no... ^" # Lucien
dialog70 = "Heh heh heh, stupid boy. Come back to me, and I will forgive. Turn away, and I will make you suffer the most painful death imaginable. ^" # The Keeper
dialog71 = "I cannot, father. I cannot. ^" # Lucien
dialog72 = "I see. In that case... ^" # The Keeper
dialog73 = "HAHAHA!!! ^" # The Keeper
dialog74 = "Lucien hasn't come back yet. Should we go look for him? I'm getting kinda nervous. ^" # Sakura
dialog75 = "Me too. Let's go try; maybe he's feeling better. ^" # Aralis
dialog76 = "Lucien! LUCIEN!!! ^" # Sakura
dialog77 = "Where did he go? Do you think something happened? ^" # Aralis
dialog78 = "Heh heh, you two are looking for that stupid outcast, are you not? ^" # The Keeper
dialog79 = "Yes! We are! Who are you, and what'd you do with him? ^" # Sakura
dialog80 = "Heh heh heh. ^" # The Keeper
dialog81 = "I know that voice...I think it's The Keeper! ^" # Aralis
dialog82 = "We've gotta hurry then, he probably hurt Lucien! ^" # Sakura
dialog83 = "LUCIEN!!! ^" # Sakura
dialog84 = "No... ^" # Aralis
dialog85 = "The Keeper must have gotten to him. He told me about how his dad oppressed him and forced him into slavery. He must've figured out that we were after him, so he did something to drive him crazy. Then he killed him. ^" # Sakura
dialog86 = "How sad... ^" # Aralis
dialog87 = "We gotta keep going though. ^" # Sakura
dialog88 = "Well well well, who do we have here? ^" # Necrothar
dialog89 = "Who are you?! ^" # Sakura
dialog90 = "I am Necrothar, the king of the castle's dead. I have been commanded to kill any on sight. So you will now die, and become my servants! ^" # Necrothar
dialog91 = "!!! ^" # Sakura
dialog92 = "How? HOW?! ^" # Necrothar
dialog93 = "Now that he's dead, we can move on from this stinking place! ^" # Sakura
dialog94 = "Wait! Sakura, what is this? It was hanging around his neck. ^" # Aralis
dialog95 = "I don't know, but it looks valuable. Wait, there's something swirling inside! ^" # Sakura
dialog96 = "Huh? ^" # Aralis
dialog97 = "Hold on, Sakura. Do you think this is what he used to raise the dead?! We might just be able to raise Lucien! ^" # Aralis
dialog98 = "We might be able to, but it looks broken. ^" # Sakura
dialog99 = "Couldn't hurt to try! ^" # Aralis
dialog100 = "Lucien? ^" # Aralis
dialog101 = "Oh... ^" # Lucien
dialog102 = "Lucien! ^" # Sakura & Aralis
dialog103 = "What...what happened? ^" # Lucien
dialog104 = "The Keeper found you and killed you, don't you remember?! ^" # Sakura
dialog105 = "Ah, I see. I remember now. ^" # Lucien
dialog106 = "Lucien, I think you owe us an explanation of what is going on. ^" # Aralis
dialog107 = "Hm, I suppose I do. I am a vampire born of my father, The Keeper, and a human from the village of Mistwood. ^" # Lucien
dialog108 = "... ^" # Aralis
dialog109 = "I see. ^" # Aralis
dialog110 = "My father was the Keeper of this castle, even before it rose from the ground. I have been despised all of my long, pitiful life, because of my parenthood. After my race discovered that my mother was a human, they mercilously tortured and then killed her. They did not dare attack my father, king of vampires, though, for fear of their lives. ^" # Lucien
dialog111 = "Lucien, I'm sorry you've gone through so much. But we're here now, and we can destroy this castle once and for all! ^" # Sakura
dialog112 = "Yes, I see that now. I suppose the good in me, given by my sweet mother, has won over. I will once again aid you in your journey. ^" # Lucien
dialog113 = "Aw so sweet! ^" # Aralis
dialog114 = "Um... ^" # Lucien
dialog115 = "Let's move on, guys. Lucien, we're happy to have you back! ^" # Sakura
dialog116 = "Be on your guard. The next section in the castle is Drake Passage, and these winged beasts have been trained to kill. ^" # Lucien
dialog117 = "What is that? ^" # Sakura
dialog118 = "I don't know, but it looks like one of those drakes has a rider! ^" # Aralis
dialog119 = "It's getting closer! ^" # Sakura
dialog120 = "Hello. I apologize for having startled you all. My name is Embreth, and this here is my pet drake Smokey. ^" # Embreth
dialog121 = "Yip yip! ^" # Smokey
dialog122 = "I am here on a journey to destroy the vile Keeper of this castle, and luckily my friend here is an escapee of these halls. ^" # Embreth
dialog123 = "Wait, so you are also aiming to vanquish the evil that is my father? ^" # Lucien
dialog124 = "Yes, I am. ^" # Embreth
dialog125 = "Well, would you like to join us? We could use another fighter. ^" # Sakura
dialog126 = "It would bring me great pleasure to accompany you on your quest, and I am confident that Smokey would enjoy it as well. I will do my best to aid you with my fire magic. ^" # Embreth
dialog127 = "I cannot begin to fathom how you have made it this far into Drake Passage without flight. Smokey can be of use there. ^" # Embreth
dialog128 = "Up ahead is Ignizar, the master of the drakes. He and his drake, Tenebrae, are a force to be reckoned with. ^" # Embreth
dialog129 = "We'll be careful. ^" # Aralis
dialog130 = "Oh hoh hoh, I'm surprised to see that you humans...and Lucien...have made it this far. I'm afraid that this is the end of the line for you, though. Tenebrae, show them your stuff! ^" # Ignizar
dialog131 = "Argh! Well, time for Plan B. ^" # Ignizar
dialog132 = "He is dead. Let us move on. ^" # Lucien
dialog133 = "Next up is the Halls of Illusion, the most cunningly deceitful portion of Bloodmoor Castle. Do not let yourself be fooled by its trickery. ^" # Lucien
dialog134 = "Okay! ^" # Sakura
dialog135 = "So, Embreth, do you know how Smokey escaped Drake Passage in the first place? ^" # Sakura
dialog136 = "I haven't the smallest inkling. All I know is that I found him in the mountains one day when he was a small little thing. ^" # Embreth
dialog137 = "But aren't you a little young to be in the exploring the mountains on your own? ^" # Sakura
dialog138 = "Yeah, how old are you anyway? ^" # Aralis
dialog139 = "I...uh...am 23. ^" # Embreth
dialog140 = "WHAAAT? There's no way. ^" # Sakura
dialog141 = "You don't look a day over 15! ^" # Aralis
dialog142 = "... ^" # Embreth
dialog143 = "FINE, I ADMIT IT! I'M 15 YEARS OLD! ^" # Embreth
dialog144 = "HAHAHA!!! ^" # Sakura & Aralis
dialog145 = "*chuckle* ^" # Lucien
dialog146 = "Hahaha... ^" # Mystara
dialog147 = "Who are you? ^" # Lucien
dialog148 = "I am Mystara, servant of The Keeper. You have entered my halls, and now you will undergo the worst form of torment. Hahaha... ^" # Mystara
dialog149 = "Elder, what happened?! I thought Florere was destroyed! ^" # Sakura
dialog150 = "No, child. I'm afraid you had a bad dream. Everything is just fine. ^" # Elder
dialog151 = "Oh... ^" # Sakura
dialog152 = "Who...are you? ^" # Aralis
dialog153 = "What do you mean, sweetie? We are your parents. ^" # Mother
dialog154 = "MOM! DAD! *sob* ^" # Aralis
dialog155 = "Huh? What is going on- ^" # Embreth
dialog156 = "ELLA! ^" # Embreth
dialog157 = "Yes, Embreth? ^" # Ella
dialog158 = "What have you done? ^" # Lucien
dialog159 = "They are now under my spell. The inescapable fear of reality has overcome them. You, though, you are stronger than they, are you not? ^" # Mystara
dialog160 = "No. I am no stronger than they. I have lived a tortuous life since my birth, and I have not seen peace. Your spells have no effect on me. ^" # Lucien
dialog161 = "Now die, you scum. ^" # Lucien
dialog162 = "This...this can't be real. I was just at the castle! I gotta get outta here! ^" # Sakura
dialog163 = "What are you doing, child? Today is a beautiful day, let's go relax over by the cherry blossom trees. ^" # Elder
dialog164 = "This isn't right. What is going on here?! ^" # Sakura
dialog165 = "Hmph. I see I can't persuade you, then. In that case... ^" # Elder
dialog166 = "Come and find me! ^" # Mystara
dialog167 = "This ends now! I won't be tricked by you! ^" # Sakura
dialog168 = "!!! ^" # Mystara
dialog169 = "This is not over. ^" # Mystara
dialog170 = "What is wrong, dear Aralis? Is something wrong? ^" # Mother
dialog171 = "No, mother. Everything is right. ^" # Aralis
dialog172 = "Wait. No, it's not. I was at the castle just now, and now I'm here. What is this? ^" # Aralis
dialog173 = "This is home, and we are your parents. ^" # Father
dialog174 = "No. My parents died years ago. This is some kind of trick... ^" # Aralis
dialog175 = "Aralis! Wait! ^" # Mother
dialog176 = "Aralis. What are you doing? Come back home with us. ^" # Father
dialog177 = "We miss you. ^" # Mother
dialog178 = "This is some kind of trick! I won't fall for it! ^" # Aralis
dialog179 = "I see then. ^" # Father
dialog180 = "I suppose I'll just have to face you myself. ^" # Mystara
dialog181 = "AH! ^" # Aralis
dialog182 = "You have not yet won. ^" # Mystara
dialog183 = "Ella, is it really you? ^" # Embreth
dialog184 = "It's been so long, Embreth. I've missed you. ^" # Ella
dialog185 = "But what about the fire? ^" # Embreth
dialog186 = "What do you mean? What fire? ^" # Ella
dialog187 = "This is wrong. Ella died in the fire that I accidentally caused. This is some kind of mind trick. ^" # Embreth
dialog188 = "What do you mean, brother? You never caused a fire! ^" # Ella
dialog189 = "Yes, I did. Stop putting lies into my head! ^" # Embreth
dialog190 = "Stop running, Embreth! ^" # Ella
dialog191 = "NO! Stop it! You are not my sister! ^" # Embreth
dialog192 = "So I can't fool you either? You three are a stubborn bunch. ^" # Mystara
dialog193 = "Hmph. The game is up then. ^" # Mystara
dialog194 = "You all are so annoying! ^" # Mystara
dialog195 = "Are you three unharmed? ^" # Lucien
dialog196 = "I'm fine. He messed with my mind. ^" # Sakura
dialog197 = "This tyrant must be destroyed once and for all. ^" # Embreth
dialog198 = "Hahaha... ^" # Mystara
dialog199 = "NOOOOO!!! ^" # Mystara
dialog200 = "She is defeated. ^" # Lucien
dialog201 = "What happened to you all? ^" # Lucien
dialog202 = "That woman...she made me see my parents again. ^" # Aralis
dialog203 = "I saw my sister, Ella. ^" # Embreth
dialog204 = "I was at my home village. ^" # Sakura
dialog205 = "She was a mastermind of deception, an evil deceiver. But she is now dead, and we shall move on if you so feel like it. ^" # Lucien
dialog206 = "But why didn't she affect you, Lucien? ^" # Sakura
dialog207 = "Mystara's one limitation was that she could only show visions of joy and peace, neither of which I have experienced. ^" # Lucien
dialog208 = "... ^" # Aralis
dialog209 = "The castle's Ruins lie ahead. This area has been forgotten by The Keeper, and has been left to rot. Tread carefully. ^" # Lucien
dialog210 = "? ^" # Sakura
dialog211 = "AH! ^" # Aralis
dialog212 = "Who is there?! ^" # Embreth
dialog213 = "Hello, travelers. I am a guardian of the Ruins, and I will not suffer to allow trespassers past this point. You will not enter my tribe. ^" # Mori
dialog214 = "We desire to pass through peacefully. The tyranny of my father's reign will stop with us. ^" # Lucien
dialog215 = "The Keeper forgotten this place, and we are happy that he did. I fear disturbing him would bring his wrath upon this place. You shall not trespass! ^" # Mori
dialog216 = "Hooo... ^" # Mori
dialog217 = "You have proven yourselves to be mighty warriors, and I am no match for the likes of you. If you will guarantee my tribe's safety, I will aid you in your quest. ^" # Mori
dialog218 = "What is your name? ^" # Aralis
dialog219 = "My name is Mori, the noble panda. ^" # Mori
dialog220 = "... ^" # Sakura & Aralis
dialog221 = "YOU ARE SO CUTE!!! ^" # Sakura & Aralis
dialog222 = "Umm... ^" # Mori
dialog223 = "What is this vile creature? ^" # Lucien
dialog224 = "This plant is the source of the vines spread throughout The Ruins. It is greatly enraged, the Thornroot. ^" # Mori
dialog225 = "I cannot believe it...for centuries we have attempted to destroy the Thornroot and to no avail! ^" # Mori
dialog226 = "You are truly the noblest of warriors. I thank you. ^" # Mori
dialog227 = "Right! ^" # Sakura
dialog228 = "Hm...The Clockworks. The most dangerous of creatures lie in wait before us. ^" # Lucien
dialog229 = "Lucien, what are you doing here? ^" # The Clockmaker
dialog230 = "I have come to thwart my father's evil plans, and kill him if necessary. If you stand in our way, Clockmaker, you will die. ^" # Lucien
dialog231 = "Hmph! You honestly think you are any match for me? I am your father's right hand man, and you will obey me! ^" # The Clockmaker
dialog232 = "Oh, you are stronger than I thought, Lucien. Well, luckily I have another trick up my sleeve... ^" # The Clockmaker
dialog233 = "!!! ^" # Lucien
dialog234 = "Where are we? Aren't we supposed to be in The Clockworks? ^" # Aralis
dialog235 = "We seem to be back where we started. This seems to be one of his illusions. ^" # Lucien
dialog236 = "That wretch! We must track him down! ^" # Embreth
dialog237 = "Ahaha...it seems you have found me." # The Clockmaker
dialog238 = "What are you doing to us? ^" # Mori
dialog239 = "Use your brain, fools. I am the master of time. I am merely transporting you back. ^" # The Clockmaker
dialog240 = "But I was never here. I came in through Drake Passage- ^" # Embreth
dialog241 = "DO NOT ASK QUESTIONS THAT INTERFERE WITH THE FACTUAL INTEGRITY OF THE STORY!!! ^" # The Clockmaker
dialog242 = "*sigh* ^" # The Clockmaker
dialog243 = "It seems we've got you cornered! ^" # Sakura
dialog244 = "Surrender now, you filth. ^" # Mori
dialog245 = "Lucien, I remember when you were but a boy. You have grown up now, and humbled me. I surrender. ^" # The Clockmaker
dialog246 = "Hmm... ^" # Lucien
dialog247 = "What's going on?! ^" # Aralis
dialog248 = "It feels as if- ^" # Lucien
dialog249 = "The castle is shaking! ^" # Embreth
dialog250 = "We must flee! ^" # Mori
dialog251 = "You irritate me so, fools! I have sent all my creatures against you and you have somehow prevailed against them! I WILL KILL YOU ALL!!! ^" # The Keeper
dialog252 = "HHHHHHAAAAAAAAAAAAAAAAA!!! ^" # The Keeper
dialog253 = "My father is enraged. His fury is tearing apart the castle. We must hurry through the Inner Sanctum and destroy him! ^" # Lucien
dialog254 = "HHHHHHAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!!! ^" # The Keeper
dialog255 = "Father, please- ^" # Lucien
dialog256 = "DO NOT TALK TO ME BOY. GET READY TO DIIIIIE!!! ^" # The Keeper
dialog257 = "... ^" # Lucien
dialog258 = "No...no...NOOOOOOO!!! ^" # The Keeper
dialog259 = "Father, your reign of terror is over. You must die so that the people of this world may not suffer any longer! ^" # Lucien
dialog260 = "For the good of the world- ^" # Sakura
dialog261 = "For those we love- ^" # Aralis
dialog262 = "For justice- ^" # Embreth
dialog263 = "For honor- ^" # Mori
dialog264 = "You must PERISH. ^" # Lucien
dialog265 = "HHHHHHHHHHHHWWWWWWWWWWWWWWWWWAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!!! ^" # The Keeper
dialog266 = "What's going on now?! ^" # Sakura
dialog267 = "The castle...IT IS CRUMBLING!!! ^" # Lucien
dialog268 = "AHHHHHHHHHHHHHHHH!!! ^" # All
dialog269 = "Smokey, you rascal! You saved us all! ^" # Embreth
dialog270 = "Yip yip! ^" # Smokey
dialog271 = "No...it cannot be... ^" # Lucien
dialog272 = "FATHER!!! You must cease this madness! ^" # Lucien
dialog273 = "I WILL NOT SUFFER YOUR INSOLENCE ANY LONGER!!! ^" # Dragon
dialog274 = "We can't reach him! ^" # Sakura
dialog275 = "Embreth, fly us closer. I know what must be done. ^" # Lucien
dialog276 = "Lucien, what are you doing? ^" # Mori
dialog277 = "Trust me. Thank you all. The four of you are the only friends I have evr had. I finally know what peace feels like. ^" # Lucien
dialog278 = "Goodbye. ^" # Lucien
dialog279 = "NO!!! LUCIEN!!! ^" # Aralis
dialog280 = "Father, it is time you die. I cannot permit you to ruin lives anymore. ^" # Lucien
dialog281 = "No...NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO!!! ^" # Dragon
dialog282 = "Hmm. He did what must be done. A true friend he was. ^" # Embreth
dialog283 = "Ahh, it feels so good to be back in Florere. The rebuilding process will take a few years. ^" # Sakura
dialog284 = "Ella...is that you? ^" # Embreth
dialog285 = "Liora? Come and eat! You too, Embreth! ^" # Aralis
dialog286 = "Alright, old friend. It's time we part. Be safe out there, Smokey. ^" # Embreth
dialog287 = "Thank you all for the service you have accomplished. Noblest of heroes, the history books will tell of our story. I am honored to have fought beside you all, but now I must return to my tribe. Lucien will be remembered. ^" # Mori
dialog288 = "... ^" # Lucien
dialog289 = "Hm. ^" # Lucien
shop_dialog = "Is there anything you need?"

# Japanese
jp_dialog0 = "城の入り口まで来たようだね。あなたが本当に強いのなら、私を見つけて証明してください。^"
jp_dialog1 = "。。。？ ^"
jp_dialog2 = "うーん。到着したようだね。^"
jp_dialog3 = "この大群を世に放ったのはお前か？ ^"
jp_dialog4 = "残念ながら、そうではない。私は彼の下僕に過ぎず、不法侵入者は問答無用で殺すよう命じられている。さあ、滅びなさい。^"
jp_dialog5 = "理解できない。あなたは誰ですか？ ^"
jp_dialog6 = "私の名はサクラ、フローレールの忍者だ。この村に大群を放った化け物を退治しに来た！ ^"
jp_dialog7 = "フン。正直に言うと、君の言う『怪物』とは私の父のことだ。彼はこの城の番人として知られており、君の言う攻撃の責任者だ。^"
jp_dialog8 = "そして君は、このキーパーという男の息子で、この城に運よく入ってこようとする者を滅ぼすために送り込まれたんだ。どこにいるんだ？ ^"
jp_dialog9 = "父は城の奥深く、内陣の玉座に座っている。^"
jp_dialog10 = "ところで、なぜ私にこの話を？あなたは悪者じゃないんですか？ ^"
jp_dialog11 = "この城の番人は抑圧的な主人で、何年もの間、彼の強引な隷属に従わなければ死ぬと脅されてきた。あなたのような方がいれば、この重荷から解放されると信じています。^"
jp_dialog12 = "僕と一緒にやりたいってこと？ ^"
jp_dialog13 = "そうだ。あなたの援助があれば、私は共通の敵を打ち負かすことができると信じています。私を生涯にわたって虐げ、苦しめてきた者を。^"
jp_dialog14 = "まあいい、約束を破らなければね。^"
jp_dialog15 = "私、ルシアンは謙虚に、そして謹んで、私が生きている限り、あなたの探求を見捨てないと誓います。^"
jp_dialog16 = "ルシアン、あなたには良いところがあるでしょ？ ^"
jp_dialog17 = "。。。^"
jp_dialog18 = "油断は禁物だ。ここはブラッドムーア城の最大の区画であり、多くの危険な生物が潜んでいる。^"
jp_dialog19 = "気をつけるよ。^"
jp_dialog20 = "ルシアン、ちょっと気づいたことがあるんだ。君はいつも派手なことを言うね。^"
jp_dialog21 = "え？ ^"
jp_dialog22 = "ああ、君はいつもオフィシャルな感じだね。少しは肩の力を抜いたらどうだ？ ^"
jp_dialog23 = "こんな些細なことが、なぜあなたにとって意味があるのですか？ ^"
jp_dialog24 = "ハハハ！ ^"
jp_dialog25 = "私たちはここにいる。この隣のドアの向こうに、本堂の守護者がいる。悪名高き3つの頭を持つ殺人犬...スポット。^"
jp_dialog26 = "待て待て、この「悪名高い殺人犬」の名前は「スポット」なのか？ハハハ！ ^"
jp_dialog27 = "笑い事ではない！この犬はキーパーの命令で多くの命を奪ってきた。近くにいろ。^"
jp_dialog28 = "わかったよ、でもまだ笑えるよ。^"
jp_dialog29 = "冗談じゃなかったね、ルシアン。あれはタフだった。^"
jp_dialog30 = "そう、実に手強い敵だ。さようなら、愛する老ペット。^"
jp_dialog31 = "うーん、うーん、うーん。なんて可愛いんだろう。^"
jp_dialog32 = "お願い、傷つけないで。^"
jp_dialog33 = "使用人よ、この惨めな女を逃がすな。拷問に訴えることはできても、決して殺してはならない。彼女には用がある。^"
jp_dialog34 = "君は可愛いね。^"
jp_dialog35 = "いいえ！ ^"
jp_dialog36 = "ここから出なきゃ。弓を取り戻したら、逃げられる。^"
jp_dialog37 = "嗚呼、弓を手に入れたからには、ここから出ることができる。^"
jp_dialog38 = "近寄らないでください！ ^"
jp_dialog39 = "あなたは誰？ ^"
jp_dialog40 = "私は誰？ ^"
jp_dialog41 = "フローレの忍者、桜巻町！ ^"
jp_dialog42 = "ルシアン、キーパーの息子。^"
jp_dialog43 = "悪党どもを放っておくわけにはいかないだろう？ ^"
jp_dialog44 = "。。。^"
jp_dialog45 = "助けてくれてありがとう。^"
jp_dialog46 = "フン。問題ない。しかし、我々はすぐにこの地域から避難しなければならない。^"
jp_dialog47 = "私も連れて行くの？ ^"
jp_dialog48 = "キーパーを破壊しようとしている以上、出口を示すことはできない。でも、十分に遠くまで連れて行くことはできる！ ^"
jp_dialog49 = "私は。。。私は。。。 ^"
jp_dialog50 = "ありがとう。キーパーみたいな不気味な奴らにこれ以上怯えさせておけないし、正しいことのために立ち上がらなきゃいけない！あなたと一緒に行きたい。^"
jp_dialog51 = "そうかもしれないが、道中には危険が待ち受けていることを承知しておいてほしい。^"
jp_dialog52 = "そうだね！ ^"
jp_dialog53 = "それで、アラリスなのか？そもそもどうやってこの城に入ったのか教えてください。^"
jp_dialog54 = "私は軍のヒーラーとして村から召喚された。私は自分の力を使って、邪悪なクリーチャーによって負傷した兵士たちの傷の手当てをした。キーパーは私の使い道を見いだして、他の者たちと一緒に私を殺す代わりに、私を捕らえ、怪物や下僕のための癒し手であることを強要しようとした。^"
jp_dialog55 = "なるほど。どうして弓矢がそんなに上手になったんですか？ ^"
jp_dialog56 = "私はミストウッド村で育った。赤ん坊のときに両親を亡くし、村人に引き取られた。新しい父は生活のために弓矢を作って売り、私にその扱い方を教えてくれた。^"
jp_dialog57 = "失礼ですが、今『ミストウッド』とおっしゃいましたか？ ^"
jp_dialog58 = "はい。なぜだ、ルシアン？ ^"
jp_dialog59 = "気にしないで。^"
jp_dialog60 = "。。。^"
jp_dialog61 = "城の地下墓地に到着した。ここは慎重に歩こう。城の死者の多くが蘇るだろうから。^"
jp_dialog62 = "そうだね。^"
jp_dialog63 = "そうだね。^"
jp_dialog64 = "ルシアン、大丈夫？いつもより悲しそうだけど。^"
jp_dialog65 = "私は。。。大丈夫です。少し席を外すよ。ついて来ないでください。^"
jp_dialog66 = "でも- ^"
jp_dialog67 = "ほっといてくれ！ ^"
jp_dialog68 = "ルシアン、ルシアン、バカ息子。何をしているんだ？この惨めなパーティに参加することを真剣に考えているのか？私の生き物を破壊するのか？父上を見捨てるのか？ ^"
jp_dialog69 = "父さん、だめだ。。。^"
jp_dialog70 = "へっへっへっへっ、バカ息子。私のもとに戻ってくれば許してやる。目を背ければ、想像を絶する苦痛を味わわせてやる。^"
jp_dialog71 = "できません、お父さん。できません。^"
jp_dialog72 = "なるほど。それなら。。。^"
jp_dialog73 = "ハハハ！^"
jp_dialog74 = "ルシアンはまだ戻ってこない。探しに行こうか？ちょっと不安になってきた。^"
jp_dialog75 = "僕もだよ。行ってみよう。もしかしたら、彼は良くなっているかもしれない。^"
jp_dialog76 = "ルシアン！ルシアン！ ^"
jp_dialog77 = "彼はどこに行ったのか？何かあったと思いますか？ ^"
jp_dialog78 = "へっへっへ、二人ともあのバカな追放者を探しているんだろ？ ^"
jp_dialog79 = "はい！そうだ あなたは誰？彼をどうしたの？ ^"
jp_dialog80 = "へっへっへっへ。^"
jp_dialog81 = "この声知ってる。。。キーパーだと思う！^"
jp_dialog82 = "ルシアンを傷つけたかもしれない！ ^"
jp_dialog83 = "ルシアン！ ^"
jp_dialog84 = "いや。。。^"
jp_dialog85 = "キーパーが彼に近づいたんだ。親父に虐げられて、奴隷にさせられたって。彼は、私たちが彼を追っていることを察知し、彼を狂わせるために何かしたに違いない。そして殺した。^"
jp_dialog86 = "なんて悲しいんだろう。。。^"
jp_dialog87 = "でも続けなきゃね。^"
jp_dialog88 = "おやおや、誰がいるのかな？ ^"
jp_dialog89 = "あなたは誰ですか？ ^"
jp_dialog90 = "私はネクロター、城の死者の王だ。見つけ次第殺せと命じられている。だから、お前たちは死んで、私の下僕になるのだ！ ^"
jp_dialog91 = "！！！^"
jp_dialog92 = "どうやって？どうやって？！ ^"
jp_dialog93 = "彼が死んだ今、我々はこの臭い場所から先に進むことができる！ ^"
jp_dialog94 = "待って！サクラ、これは何？首にぶら下がっていた。^"
jp_dialog95 = "よくわからないけど、貴重品に見える。待って、中で何かが渦巻いている！ ^"
jp_dialog96 = "え？ ^"
jp_dialog97 = "ちょっと待って、サクラ。これが死者を蘇らせるのに使ったと思う？ルシアンを蘇らせることができるかもしれない！ ^"
jp_dialog98 = "できるかもしれないが、壊れているようだ。^"
jp_dialog99 = "やってみても損はないだろう！ ^"
jp_dialog100 = "ルシアン？ ^"
jp_dialog101 = ""
jp_dialog102 = ""
jp_dialog103 = ""
jp_dialog104 = ""
jp_dialog105 = ""
jp_dialog106 = ""
jp_dialog107 = ""
jp_dialog108 = ""
jp_dialog109 = ""
jp_dialog110 = ""
jp_dialog111 = ""
jp_dialog112 = ""
jp_dialog113 = ""
jp_dialog114 = ""
jp_dialog115 = ""
jp_dialog116 = ""
jp_dialog117 = ""
jp_dialog118 = ""
jp_dialog119 = ""
jp_dialog120 = ""
jp_dialog121 = ""
jp_dialog122 = ""
jp_dialog123 = ""
jp_dialog124 = ""
jp_dialog125 = ""
jp_dialog126 = ""
jp_dialog127 = ""
jp_dialog128 = ""
jp_dialog129 = ""
jp_dialog130 = ""
jp_dialog131 = ""
jp_dialog132 = ""
jp_dialog133 = ""
jp_dialog134 = ""
jp_dialog135 = ""
jp_dialog136 = ""
jp_dialog137 = ""
jp_dialog138 = ""
jp_dialog139 = ""
jp_dialog140 = ""
jp_dialog141 = ""
jp_dialog142 = ""
jp_dialog143 = ""
jp_dialog144 = ""
jp_dialog145 = ""
jp_dialog146 = ""
jp_dialog147 = ""
jp_dialog148 = ""
jp_dialog149 = ""
jp_dialog150 = ""
jp_dialog151 = ""
jp_dialog152 = ""
jp_dialog153 = ""
jp_dialog154 = ""
jp_dialog155 = ""
jp_dialog156 = ""
jp_dialog157 = ""
jp_dialog158 = ""
jp_dialog159 = ""
jp_dialog160 = ""
jp_dialog161 = ""
jp_dialog162 = ""
jp_dialog163 = ""
jp_dialog164 = ""
jp_dialog165 = ""
jp_dialog166 = ""
jp_dialog167 = ""
jp_dialog168 = ""
jp_dialog169 = ""
jp_dialog170 = ""
jp_dialog171 = ""
jp_dialog172 = ""
jp_dialog173 = ""
jp_dialog174 = ""
jp_dialog175 = ""
jp_dialog176 = ""
jp_dialog177 = ""
jp_dialog178 = ""
jp_dialog179 = ""
jp_dialog180 = ""
jp_dialog181 = ""
jp_dialog182 = ""
jp_dialog183 = ""
jp_dialog184 = ""
jp_dialog185 = ""
jp_dialog186 = ""
jp_dialog187 = ""
jp_dialog188 = ""
jp_dialog189 = ""
jp_dialog190 = ""
jp_dialog191 = ""
jp_dialog192 = ""
jp_dialog193 = ""
jp_dialog194 = ""
jp_dialog195 = ""
jp_dialog196 = ""
jp_dialog197 = ""
jp_dialog198 = ""
jp_dialog199 = ""
jp_dialog200 = ""
jp_dialog201 = ""
jp_dialog202 = ""
jp_dialog203 = ""
jp_dialog204 = ""
jp_dialog205 = ""
jp_dialog206 = ""
jp_dialog207 = ""
jp_dialog208 = ""
jp_dialog209 = ""
jp_dialog210 = ""
jp_dialog211 = ""
jp_dialog212 = ""
jp_dialog213 = ""
jp_dialog214 = ""
jp_dialog215 = ""
jp_dialog216 = ""
jp_dialog217 = ""
jp_dialog218 = ""
jp_dialog219 = ""
jp_dialog220 = ""
jp_dialog221 = ""
jp_dialog222 = ""
jp_dialog223 = ""
jp_dialog224 = ""
jp_dialog225 = ""
jp_dialog226 = ""
jp_dialog227 = ""
jp_dialog228 = ""
jp_dialog229 = ""
jp_dialog230 = ""
jp_dialog231 = ""
jp_dialog232 = ""
jp_dialog233 = ""
jp_dialog234 = ""
jp_dialog235 = ""
jp_dialog236 = ""
jp_dialog237 = ""
jp_dialog238 = ""
jp_dialog239 = ""
jp_dialog240 = ""
jp_dialog241 = ""
jp_dialog242 = ""
jp_dialog243 = ""
jp_dialog244 = ""
jp_dialog245 = ""
jp_dialog246 = ""
jp_dialog247 = ""
jp_dialog248 = ""
jp_dialog249 = ""
jp_dialog250 = ""
jp_dialog251 = ""
jp_dialog252 = ""
jp_dialog253 = ""
jp_dialog254 = ""
jp_dialog255 = ""
jp_dialog256 = ""
jp_dialog257 = ""
jp_dialog258 = ""
jp_dialog259 = ""
jp_dialog260 = ""
jp_dialog261 = ""
jp_dialog262 = ""
jp_dialog263 = ""
jp_dialog264 = ""
jp_dialog265 = ""
jp_dialog266 = ""
jp_dialog267 = ""
jp_dialog268 = ""
jp_dialog269 = ""
jp_dialog270 = ""
jp_dialog271 = ""
jp_dialog272 = ""
jp_dialog273 = ""
jp_dialog274 = ""
jp_dialog275 = ""
jp_dialog276 = ""
jp_dialog277 = ""
jp_dialog278 = ""
jp_dialog279 = ""
jp_dialog280 = ""
jp_dialog281 = ""
jp_dialog282 = ""
jp_dialog283 = ""
jp_dialog284 = ""
jp_dialog285 = ""
jp_dialog286 = ""
jp_dialog287 = ""
jp_dialog288 = ""
jp_dialog289 = ""